#!/bin/bash
for filename in `ls *.bin`;
do
  basefilename=`basename $filename .bin`
  unscrambled_filename=`echo $basefilename | openssl enc -a -d`
  printf "%-50s | %-50s\n" $filename $unscrambled_filename 
done
