#!/bin/bash
for filename in `ls *.bin`;
do
  basefilename=`basename $filename .bin`
  unscrambled_filename=`echo $basefilename | openssl enc -a -d`
  printf "%-40s | %-40s\n" $unscrambled_filename $filename 
done
